name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - run: pnpm install

      - name: Build
        run: pnpm run dev:prepare && pnpm run build

      - name: Install nuxt3 dependencies
        run: cd playground/nuxt3 && pnpm install && pnpm prepare

      - name: Run tests
        run: pnpm run test
