name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        node: [ 14 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build ts
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Coverage
        uses: codecov/codecov-action@v1
